INSERT INTO USER (USERNAME, PASSWORD, BLOCKED) VALUES ('admin', 'admin', false );
INSERT INTO USER (USERNAME, PASSWORD, BLOCKED) VALUES ('user', 'user', false );
INSERT INTO USER (USERNAME, PASSWORD, BLOCKED) VALUES ('111', '111', false );
INSERT INTO USER (USERNAME, PASSWORD, BLOCKED) VALUES ('222', '222', false );

INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('user', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('admin', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('admin', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('111', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('222', 'USER');
