INSERT INTO USER (USERNAME, PASSWORD) VALUES ('admin', 'admin');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('user', 'user');

INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('user', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('admin', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('admin', 'USER');
